--CREATE SCHEMA POLICE

use Projeto

/* Apagar tabelas
DROP TABLE POLICE.PESSOA;
*/

CREATE TABLE POLICE.PESSOA(
	nome				VARCHAR(90)		NOT NULL,
	Ncc					VARCHAR(30)		NOT NULL,
	Bdate				DATE,
	morada				VARCHAR(90),
	sexo				VARCHAR(90)		NOT NULL,
	PRIMARY KEY (Ncc),
);

CREATE TABLE POLICE.POLICIA(
	id					VARCHAR(30)				NOT NULL,
	cc					VARCHAR(30),
	lugar				VARCHAR(90)				NOT NULL,
	Ntelefone			CHAR(9),
	IDEquipa			VARCHAR(30)				DEFAULT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (cc) REFERENCES POLICE.PESSOA(Ncc)  ON UPDATE CASCADE,
	--FOREIGN KEY (id_equipa) REFERENCES POLICE.EQUIPA(E_id),
);

CREATE TABLE POLICE.EQUIPA(
	PPid				VARCHAR(30),
	Eid					VARCHAR(30)				NOT NULL,
	PRIMARY KEY (Eid),
	FOREIGN KEY (PPid) REFERENCES POLICE.POLICIA(id),-- ON DELETE SET NULL ON UPDATE CASCADE,
);

ALTER TABLE POLICE.POLICIA 
ADD CONSTRAINT PPOLEID FOREIGN KEY (IDEquipa) REFERENCES POLICE.EQUIPA(Eid) ON DELETE SET NULL ON UPDATE CASCADE;


CREATE TABLE POLICE.DETENCAO(
	codigo				VARCHAR(30)				NOT NULL,
	DataBD				DATE					DEFAULT NULL,
	DataDetencao		DATE,
	CrimeCodigo			VARCHAR(30)				DEFAULT NULL,
	EquipaID			VARCHAR(30),
	PoliciaInfID		VARCHAR(30)				DEFAULT NULL,
	Ncriminosos			INT						DEFAULT 1,
	PRIMARY KEY (codigo),
	--FOREIGN KEY (crime_codigo) REFERENCES POLICE.CRIME(codigo),
	FOREIGN KEY (EquipaID) REFERENCES POLICE.EQUIPA(Eid),
	FOREIGN KEY (PoliciaInfID) REFERENCES POLICE.POLICIA(id) ON DELETE SET NULL ON UPDATE CASCADE,
);

CREATE TABLE POLICE.SUSPEITO(
	cc					VARCHAR(30)		NOT NULL,
	NCrimesEfetuados	VARCHAR(30)		DEFAULT 0,
	PRIMARY KEY (cc),
	FOREIGN KEY (cc) REFERENCES POLICE.PESSOA(Ncc) ON UPDATE CASCADE,
);


CREATE TABLE POLICE.CRIME(
	codigo					VARCHAR(30)				NOT NULL,
	--SuspCC					VARCHAR(30),
	localizacao				VARCHAR(30),
	tipo					VARCHAR(30),
	PRIMARY KEY (codigo),
);

ALTER TABLE POLICE.DETENCAO 
ADD CONSTRAINT PDETFK FOREIGN KEY (CrimeCodigo) REFERENCES POLICE.CRIME(codigo);

CREATE TABLE POLICE.VEICULOS(
	EquipaID					VARCHAR(30),
	matricula					VARCHAR(30)		NOT NULL,
	categoria					VARCHAR(15),
	CrimeCodigo					VARCHAR(30),
	DetCod						VARCHAR(30),
	PRIMARY KEY (matricula, CrimeCodigo),
	FOREIGN KEY (EquipaID) REFERENCES POLICE.EQUIPA(Eid),
	FOREIGN KEY (CrimeCodigo) REFERENCES POLICE.CRIME(codigo),
	FOREIGN KEY (DetCod) REFERENCES POLICE.DETENCAO(codigo) ON UPDATE CASCADE,

);

CREATE TABLE POLICE.DETSUSP(
	SuspCC					VARCHAR(30)		NOT NULL,
	DetCodigo				VARCHAR(30)		NOT NULL,
	PRIMARY KEY (SuspCC, DetCodigo),
	FOREIGN KEY (SuspCC) REFERENCES POLICE.SUSPEITO(cc),
	FOREIGN KEY (DetCodigo) REFERENCES POLICE.DETENCAO(codigo),
);

CREATE TABLE POLICE.CRIMESUSP(
	SuspCC					VARCHAR(30)		NOT NULL,
	CrimeCod				VARCHAR(30)		NOT NULL,
	PRIMARY KEY (SuspCC, CrimeCod),
	FOREIGN KEY (SuspCC) REFERENCES POLICE.SUSPEITO(cc),
	FOREIGN KEY (CrimeCod) REFERENCES POLICE.CRIME(codigo) ON UPDATE CASCADE,
);